version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
